In [1]:
import numpy as np

In [2]:
my_list=[-17,0,4,5,9]
my_array_from_list=np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [3]:
my_array_from_list*10

array([-170,    0,   40,   50,   90])

In [4]:
my_array_from_list-1

array([-18,  -1,   3,   4,   8])

In [5]:
my_array_from_list*10-1

array([-171,   -1,   39,   49,   89])

In [7]:
my_vector=np.array([-17,-4,0,2,21,37,105])

In [8]:
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [9]:
my_vector[0]

-17

In [10]:
my_vector[-3]

21

In [11]:
my_vector.size

7

In [12]:
my_array=np.arange(35)
my_array.shape=(7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [13]:
my_array[2]

array([10, 11, 12, 13, 14])

In [14]:
my_array[5,2]

27

In [15]:
my_array[5][2]

27